config/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('common/', include('django.contrib.auth.urls')),
    path('',views.index,name='index'),
]

main/urls.py
from django.urls import path
# from .views import index, detail, answer_create
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:id>/<int:comment_id>/', views.detail, name = "detail"),
    path('comment/create/<str:id>/<int:num>', views.comment_create, name='comment_create'),
    path('comment/modify/<str:id>/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<str:id>/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    #path('camping_detail/', views.camping_detail, name='camping_detail'),   
    path('db/', views.db, name='db'),
    path('receive_data/', views.receive_data, name='receive_data'),

    path('answer/create/<str:id>/<int:comment_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<str:id>/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<str:id>/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    
    path('vote/comment/<str:id>/<int:comment_id>', views.vote_comment, name = "vote_comment"),
    path('vote/answer/<str:id>/<int:answer_id>', views.vote_answer, name = "vote_answer"),
    
    path('location/', views.location, name='location'),
    path('location/<str:id>/', views.location_detail, name='location_detail'),
    path('camping_detail/<str:id>/<int:num>', views.camping_detail, name='camping_detail'), 

    path('search/', views.search, name="search"),
    path('search/<str:radio>/<str:search>', views.search_val, name="search_val"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class camping(models.Model):
    name = models.CharField(max_length=100,null=True)
    type = models.CharField(max_length=20,null=True)
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)
    location = models.CharField(max_length=100,null=True)
    location2 = models.CharField(max_length=100,null=True)
    phone = models.CharField(max_length=25,null=True)
    people = models.IntegerField(null=True)
    facilities = models.CharField(max_length=100,null=True)
    safefacilities = models.CharField(max_length=100,null=True)
    otherfacilities = models.CharField(max_length=100,null=True)
    time  = models.CharField(max_length=100,null=True)
    cost = models.CharField(max_length=500,null=True)
    managerphone = models.CharField(max_length=25,null=True)
    manager = models.CharField(max_length=100,null=True)
    managelocation = models.CharField(max_length=100,null=True)

    def __str__(self):
        return self.name

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='author_comment')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField() #글 등록할 때 timezone으로부터 받아옴
    modify_date = models.DateTimeField(null=True, blank=True)
    camping_id = models.ForeignKey(camping, on_delete=models.CASCADE, null=True )
    voter = models.ManyToManyField(User, related_name='voter_comment')

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='author_answer')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')
    def __str__(self):
        return self.content

main/forms.py
from django import forms
from main.models import Comment, Answer

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'content']

        widgets = {
            'subject' : forms.TextInput(attrs={'class':'form-control'}),
            'content' : forms.Textarea(attrs={'class': 'form-control', 'rows': 10})
        }
        labels = {
            'subject':'제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
        'content': '답변내용',
        }

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages
from .forms import CommentForm, AnswerForm
from .models import Comment,camping, Answer
from django.core.paginator import Paginator
# Create your views here.
def index(request):
  
    return render(request, 'main/index.html')

def detail(request,id, comment_id):
    """
    후기 내용 출력
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    data = Comment.objects.get(id = comment_id)
    number = data.camping_id.id
    print(number)
    context = {
        'comment': comment,
        'number' : number,
        'area'  : id,
        }

    return render(request, 'main/comment_detail.html', context)


@login_required(login_url='common:login')
def comment_create(request,id,num):
    """
    후기등록
    """
    camping_name = camping.objects.get(id=num)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.camping_id = camping_name
            comment.save()
            return redirect(f'main:camping_detail',id,num)
    else:
        form = CommentForm()
    
    context = {'form': form}
    return render(request, 'main/comment.html', context)


@login_required(login_url='common:login')
def comment_modify(request,id, comment_id):
    """
    후기수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    num=comment.camping_id.id
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('main:detail',id,comment_id)
    if request.method == "POST":
# 질문 수정을 위해 값 덮어쓰기
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now() # 수정일시 저장
            comment.save()
            return redirect('main:detail',id, comment_id)
    else:
        # 질문 수정 화면에 기존 제목, 내용 반영
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'main/comment.html', context)

@login_required(login_url='common:login')
def comment_delete(request,id, comment_id):
    """
    후기삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('main:detail',id, comment_id=comment.id)

    num=comment.camping_id.id

    comment.delete()
    return redirect(f'main:camping_detail',id,num)   

@login_required(login_url='common:login')
def answer_create(request,id, comment_id):
    """
    후기에 답변등록하기
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
    if form.is_valid():
        answer = form.save(commit=False)
        answer.author = request.user
        answer.create_date = timezone.now()
        answer.comment = comment
        answer.save()
        return redirect('main:detail',id, comment.id)
    else:
        form = AnswerForm()
    context = {'comment' : comment, 'form' : form}
    return render(request, 'main/comment_detail.html', id, context)

@login_required(login_url='common:login')
def answer_modify(request,id, answer_id):
    """
    질문 답변수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('main:detail',id, answer.comment.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('main:detail',id, answer.comment.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'main/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request,id, answer_id):
    """
    질문 답변삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('main:detail',id, answer.comment.id)

@login_required(login_url='common:login')
def vote_comment(request,id, comment_id):
    """
    후기추천등록
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user == comment.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        comment.voter.add(request.user)
    return redirect('main:detail',id, comment.id)

@login_required(login_url='common:login')
def vote_answer(request,id, answer_id):
    """
    후기 답글추천등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('main:detail',id,answer.comment.id)
        
def camping_detail(request,id,num):

    page = request.GET.get('page','1')
    comment_list = Comment.objects.filter(camping_id=num).order_by("-create_date")
    data_list=[]
    x=0
    for i in range(len(comment_list),0,-1):
        data_list.append({'num':i,'comment_name':comment_list[x]})
        x=x+1



    paginator = Paginator(data_list, 10)
    page_obj = paginator.get_page(page)


    print(page_obj)



    camping_name = camping.objects.get(id=num)

    context = {
        'comment_list' : page_obj,
        'camping' : camping_name,
        'area': id,
        }
  
    return render(request, 'main/camping_detail.html', context)


def db(request):
    return render(request, 'main/receive_data.html')


def receive_data(request):
    import requests
    from ast import literal_eval


    pagenum=0   #0부터 시작
    page_data = 100 #페이지당 데이터개수, 약 2220개 데이터 있는걸로 확인됨.
    total_data = 2230
    total_page = total_data//page_data


    url = 'http://api.data.go.kr/openapi/tn_pubr_public_campg_api'
    key_decoding = '/CTZDSd8CqhcX7WCXl6dU6eRaw3qVVEvNVkcGsWlgEeuKSAK2Ty94Qg4Tkwebxm1C4emTuSX+jVv5S3S1NW9rw=='
    
    
    try:
        camping_list = camping.objects.all()
        camping_list.delete()
        pass
        
    except:
        pass
    
    camping_list = camping()
    for i in range(total_page):
        print(f"## 데이터 받는중 {i}/{total_page} Page##")
        params ={'serviceKey' : key_decoding, 'pageNo' : i, 'numOfRows' : page_data, 'type' : 'json'}

        #html 통신으로 값을 받음
        response = requests.get(url, params=params)

        #txt형식(str)으로 값을 저장함
        data = response.text

        # txt형식에서 필요 데이터 추출
        start = data.find('[')
        end = data.find('],')
        item = data[start:end+1]

        # 각 데이터를 사전으로 묶고 리스트로 저장

        dic_item = literal_eval(item)

        for a in range(page_data):
            try:
                camping_list = camping(
                    # id = ((i)*10)+a,
                    name = dic_item[a]["campgNm"],
                    type = dic_item[a]["campgSe"],
                    latitude = dic_item[a]["latitude"],
                    longitude = dic_item[a]["longitude"],
                    location = dic_item[a]["rdnmadr"],
                    location2 = dic_item[a]["lnmadr"],
                    phone = dic_item[a]["officePhoneNumber"],
                    people = dic_item[a]["dayAcmdCo"],
                    facilities = dic_item[a]["cvntl"],
                    safefacilities = dic_item[a]["safentl"],
                    otherfacilities = dic_item[a]["etcty"],
                    time = dic_item[a]["useTime"],
                    cost = dic_item[a]["useCharge"],
                    managerphone = dic_item[a]["phoneNumber"],
                    manager = dic_item[a]["institutionNm"],
                    managelocation = dic_item[a]["institutionNm"],
                )
                camping_list.save()
            except:
                pass
    camping_list.save()
    return redirect('main:index')



def location(request):
    return render(request, 'location/location.html')


def location_detail(request, id):

    try:
        data = camping.objects.filter(location__contains=id).values()
        camping_list = data.order_by("location")
    except:
        camping_list = None
    
    page = request.GET.get('page','1')
    paginator = Paginator(camping_list, 20)
    page_obj = paginator.get_page(page)

    context = {
        'area' : id,
        'camping_list' : page_obj
    }

    return render(request, 'location/location_detail.html',context)


def search(request):
    # data = camping.objects.filter(location__contains=id).values()
    # camping_list = data.order_by("location")
    if request.method == "POST":
        search= request.POST.get('search', '')
        radio=request.POST.get('radioTxt','')

        if search=="":
            return render(request, 'location/location.html')

        context = {
            'search' : search,
            'radio' : radio,
        }

        return render(request, 'location/search.html',context)
    
    else:
        return render(request, 'location/location.html')


def search_val(request, radio, search):

    if radio == "name":
        try:
            data = camping.objects.filter(name__contains=search).values()
            camping_list = data.order_by("location")
        except:
            camping_list = None

    if radio == "address":
        try:
            data = camping.objects.filter(location__contains=search).values()
            camping_list = data.order_by("location")
        except:
            camping_list = None

    if radio == "facilities":
        try:

templates/main/answer_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="form-group">
        <br><br>
        <h3><i class="fas fa-pencil-alt"></i> 댓글 수정하기 </h3>
        
        <textarea class="form-control" name="content" id="content" rows="8">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary"><i class="fas fa-bookmark"></i> 저장하기</button>
        <a href = "javascript:history.back()" class="btn btn-primary"><i class="fas fa-undo"></i> 돌아가기</a>
    </form>
</div>
{% endblock %}}

templates/main/answer_list.html
<h5 class="border-bottom my-3 py-2"><i class="fas fa-reply"></i> {{comment.answer_set.count}}개의 답변이 있습니다.</h5>
{% for answer in comment.answer_set.all %}
<div class="row my-3">
  <div class="col-1"> <!-- 추천영역 -->
    <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
        {{answer.voter.count}}</div>
    <a href="{% url 'main:vote_answer' area answer.id %}" data-uri="{% url 'main:vote_answer' area answer.id %}" 
        class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
</div>
<div class="col-11"> 
<div class="card my-3">
  <div class="card-body">
    <div class="card-text" style="white-space: pre-line"><i class="fas fa-comment-dots"></i> {{ answer.content }}</div>
    <div class="d-flex justify-content-end">
      {% if answer.modify_date %}
      <div class="badge badge-light p-2 text-left">
        <div class="mb-2">작성자 : {{answer.author.username}}</div>
        <div><i class="fas fa-clock"></i>{{ answer.modify_date | date:'Y-m-d H:i:s'}}</div>
      </div>
      {% else %}
      <div class="badge badge-light p-2 text-left">
        <div class="mb-2">작성자 : {{answer.author.username}}</div>
        <div><i class="fas fa-clock"></i>{{ answer.create_date | date:'Y-m-d H:i:s'}}</div>
      </div>
      {% endif %}
  </div>
    {% if request.user == answer.author %}
    <a href="{% url 'main:answer_modify' area answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
    <a href="{% url 'main:answer_delete' area answer.id %}" class="delete btn btn-sm btn-outline-danger" data-uri="{% url 'main:answer_delete' area answer.id %}">삭제</a>
    {% endif %}
</div>
</div>
</div>
</div>
{% endfor %}

templates/main/comment.html
{% extends 'base.html' %}
{% block content%}
{% load static %}
<link href="{% static 'css/styles.css'%}" rel="stylesheet" />
<link href="{% static 'css/detail.css'%}" rel="stylesheet" />
<br><br>
<div class="container my-3">
<h3 class="my-3 border-bottom pb-2"><i class="fas fa-pencil-alt"></i> 후기등록</h3>
    <form method="post" class="post-form my-3">
        {% csrf_token%}
        {% include 'error/form_error.html' %}

        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" 
            id="subject" value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}class="form-control" name="content" id="content" 
            rows="8">{{form.content.value|default_if_none:''}}</textarea>
        </div>
        <button type="submit" class="btn btn-primary"><i class="fas fa-bookmark"></i> 후기등록</button>
        <a href = "javascript:history.back()" class="btn btn-primary"><i class="fas fa-undo"></i> 돌아가기</a>
        
    </form>
</div>
{% endblock %}

templates/main/comment_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

    <link
    rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
    integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
    crossorigin="anonymous"
    />

    <div class="container my-3">
        <div class="font-setting">
        {% if messages %}
        <br>
        <!--사용자 오류 표시-->
        <div class="alert alert-danger my-3" role="alert">
            {% for message in messages %}
                <strong>{{ message.tags }}</strong>
                <ul><li>{{ message.message }}</li></ul>
            {% endfor %}
        </div>
        {% endif %}



    <br><br>

    <h2 class="border-bottom"><i class="fas fa-search"></i> 후기 글</h2>
    <br>
    <h2 class="border-bottom py-2">{{ comment.subject }}</h2>
    <div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{comment.voter.count}}</div>
                <a href="{% url 'main:vote_comment' area comment.id %}" data-uri="{% url 'main:vote_comment' area comment.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
            </div>  
    <div class="col-11">
    <div class="card">
        <div class="card-body">
        <div class="card-text" style="white-space: pre-line">{{ comment.content }}</div>
        <div class="d-flex justify-content-end">
        {% if request.user == comment.author %}
        <div class="my-3">
            <a href="{% url 'main:comment_modify' area comment.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="{% url 'main:comment_delete' area comment.id %}" class="delete btn btn-sm btn-outline-danger" data-uri="{% url 'main:comment_delete' area comment.id %}">삭제</a>
        </div>
        {% endif %}
    </div></div></div>
    <br>
    <div class="badge badge-light p-2 text-left float-right">
        <div class="mb-2">작성자 : {{comment.author.username}}</div>
        <div><i class="fas fa-clock"></i> {{ comment.create_date | date:'Y-m-d H:i:s'}}</div>
    </div>
    <a href = "{% url 'main:camping_detail' area number %}" class="btn btn-primary"><i class="fas fa-list"></i> 목록보기</a>

</div></div>

    {% include 'main/answer_list.html' %}
    <form action="{% url 'main:answer_create' area comment.id %}" method="post">
        {% csrf_token %}
        <textarea {% if not user.is_authenticated %} disabled {% endif %} name="content" id="content" rows="5"></textarea>
        <input type="submit" value="답변등록"class="btn btn-primary">
    </form>

</div>
{% endblock content %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 글을 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });

    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
        location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/main/comment_list.html
{% block content %}
{% load static %}
<div class="camp_intro">
    <div class="camping_bigname">Review</div>
    <div class="board_w">
    <div class="my-3">
        <table class="table table-striped table-hover">
            <thead>
                <tr class="thead-dark text-center">
                    <th style="width:60px">번호</th>
                    <th>추천수</th>
                    <th>제목</th>
                    <th>작성자</th>
                    <th style="width.250px">작성날짜</th>
                </tr>
            </thead>
        
            <tbody>
            {% if comment_list %} {% for comment in comment_list %}
            <tr class="text-center">
                <td>{{ comment.num }}</td>
                <td>
                    {% if comment.comment_name.voter.all.count > 0 %}
                    <span class="badge badge-warning px-2 py-1">
                    {{ comment.comment_name.voter.all.count }}</span>
                    {% endif %}
                </td>

                <td>
                <a href="{% url 'main:detail' area comment.comment_name.id %}"> {{ comment.comment_name.subject }}</a>
                {% if comment.comment_name.answer_set.count > 0 %}
                    <span class="text-danger small ml-2"> 
                        {{ comment.comment_name.answer_set.count }}</span>
                    {% endif %}
                </td>
                <td>{{ comment.comment_name.author.username }}</td> 
                <td>{{ comment.comment_name.create_date | date:'Y-m-d' }}</td>
            </tr>
            {% endfor %} 
            {% else %}
            <tr>
                <td colspan="5">후기가 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
        <div class="clearfix">
            <div class="float-left">
            <a href="{% url 'main:comment_create' area camping.id %}" class = "btn btn-primary"><i class="fas fa-pencil-alt"></i> 후기 쓰기</a>
            </div>
            <div class="text-right float-right">(총: {{comment_list.paginator.count}}건)</div>
        </div>
    </div>
    </div>
</div>

<!--페이지네이션 부분-->
<div class=page>
<ul class="pagination">
    {% if comment_list.has_previous %}
    <li class = "page-item">
        <a class="page-link" href="?page=1"><img src="{% static 'images/btn_pre00.png'%}"></a>
    </li>
    <li class = "page-item">
        <a class="page-link" href="?page={{ comment_list.previous_page_number }}"><img src="{% static 'images/btn_pre01.png'%}"></a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><img src="{% static 'images/btn_pre00.png'%}"></a>
    </li>
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><img src="{% static 'images/btn_pre01.png'%}"></a>
    </li>
    {% endif %}
    {% for page_number in comment_list.paginator.page_range %}
    {% if page_number >= comment_list.number|add:-5 and page_number <= comment_list.number|add:5 %}
        {% if page_number == comment_list.number %}
        <li class="page-item-num active" aria-current="page">
            <a class="page-link" href="?page={{page_number}}">{{page_number}}</a>
        </li>
        {% else %}
        <li class="page-item-num">
            <a class="page-link" href="?page={{page_number}}">{{page_number}}</a>
        </li>
        {% endif %}
    {% endif %}
    {% endfor %}

    {% if comment_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{comment_list.next_page_number}}"><img src="{% static 'images/btn_next01.png'%}"></a>
    </li>
    <li class="page-item">
        <a class="page-link" href="?page={{comment_list.paginator.num_pages}}"><img src="{% static 'images/btn_next00.png'%}"></a>
    </li>
    {% else %}
    <li class = "page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><img src="{% static 'images/btn_next01.png'%}"></a>
    </li>
    <li class = "page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><img src="{% static 'images/btn_next00.png'%}"></a>
    </li>
    {% endif %}
</ul>
</div>
{% endblock %}

templates/main/index.html
{% extends "base.html" %} {% block content %}
{% load static %}
    <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    <script src="{% static 'js/move_image.js'%}"></script>

    <!--맨위 사진-->
    <section class="home" id="home">
        <img src="{% static 'images/home1.jpg'%}" alt="" class="home__img">
        
        <div class="home__container">
            
            <span class="home_main_title">
                당신의 캠핑장을 찾아보세요.
            </span>

            <span class="home_main_data">
                <br>당신과 <br>가장 어울리는 <br>캠핑장을 찾아드립니다.<br>
            </span>
            <br>
            <a href="{% url 'main:location' %}" class="button">검색</a>
            <dev class="camping_img">
                <img class="slide1" src="{% static 'images/camp2.jpg'%}" >
                <img class="slide1" src="{% static 'images/camp5.jpeg'%}" >
                <img class="slide1" src="{% static 'images/camp6.jpeg'%}" >
            <dev>
        </div>

        
    </section>

{% endblock %}

templates/main/receive_data.html
{% extends "base.html" %} {% block content %}
{% load static %}
<link href="{% static 'css/styles.css'%}" rel="stylesheet" />
<div style="margin-top : 50px;margin-left:50px;font-size:30px">
    아래 버튼을 누르면 다운로드가 진행됩니다.<br>
    버튼을 누르면 데이터가 초기화 되고 다시 다운로드됩니다.</br>
    페이지를 벗어나도 다운로드는 진행하나 되도록이면 벗어나지 말아주세요.<br>
    다운 완료 시 자동으로 메인페이지로 이동합니다</br>
    3~5분 정도 소요됩니다
    <br><br>
    관리자 이외에는 절대 누르지 마세요<br>
    한번만 누르세요
</div>
<a href="{% url 'main:receive_data' %}" class="button" style="margin-left:50px;">데이터재시작</a>
{% endblock %}