config/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('common/', include('django.contrib.auth.urls')),
    path('',views.index,name='index'),
]

main/urls.py
from django.urls import path
# from .views import index, detail, answer_create
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:id>/<int:comment_id>/', views.detail, name = "detail"),
    path('comment/create/<str:id>/<int:num>', views.comment_create, name='comment_create'),
    path('comment/modify/<str:id>/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<str:id>/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    #path('camping_detail/', views.camping_detail, name='camping_detail'),   
    path('db/', views.db, name='db'),
    path('receive_data/', views.receive_data, name='receive_data'),

    path('answer/create/<str:id>/<int:comment_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<str:id>/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<str:id>/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    
    path('vote/comment/<str:id>/<int:comment_id>', views.vote_comment, name = "vote_comment"),
    path('vote/answer/<str:id>/<int:answer_id>', views.vote_answer, name = "vote_answer"),
    
    path('location/', views.location, name='location'),
    path('location/<str:id>/', views.location_detail, name='location_detail'),
    path('camping_detail/<str:id>/<int:num>', views.camping_detail, name='camping_detail'), 

    path('search/', views.search, name="search"),
    path('search/<str:radio>/<str:search>', views.search_val, name="search_val"),
]

templates/location/location.html
{% extends 'base.html' %}
{% block content%}
{% load static %}
<link href="{% static 'css/table.css' %}" rel="stylesheet"/>
{% comment %} <link href="{% static 'css/styles.css'%}" rel="stylesheet" /> {% endcomment %}

<img src="{% static 'images/home1.jpg'%}" alt="" class="home__img">

   <div class="search">

         <form action= "{% url 'main:search' %}" method="post">
         {% csrf_token %}
            <input type="radio" name="radioTxt" value="name" checked="checked"> <span class="search-switch">캠핑장이름으로 검색</span>
            <input  type="radio" name="radioTxt" value="address"> <span class="search-switch">지역으로 검색</span>
            <input  type="radio" name="radioTxt" value="facilities"> <span class="search-switch">편의시설로 검색</span><br>
            <input class="search-text" type="text" class="form-control search" name="search">
            <input type="submit" class="search-button" type="button" id="btn_search" value = "찾기">
         </form>

   </div>



   <div class="box1">
      <div class="location">

         <li class="first_list">
            <a href="{% url 'main:location_detail' '서울특별시' %}">서울특별시</a>
               </li>
            </ul>
         </li>

         <li class="first_list">
               <a href="{% url 'main:location_detail' '경기도' %}">경기도</a>
               <ul>
         </li>
               <li>
                  <a href="{% url 'main:location_detail' '파주시' %}">파주시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '포천시' %}">포천시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '용인시' %}">용인시</a>
               </li>

               <li>
                  <a href="{% url 'main:location_detail' '시흥시' %}">시흥시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '수원시' %}">수원시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '광명시' %}">광명시</a>
               </li>

               <li>
                  <a href="{% url 'main:location_detail' '구리시' %}">구리시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '화성시' %}">화성시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '여주시' %}">여주시</a>
               </li>

               <li>
                  <a href="{% url 'main:location_detail' '양주시' %}">양주시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '김포시' %}">김포시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '동두천시' %}">동두천시</a>
               </li>

               <li>
                  <a href="{% url 'main:location_detail' '군포시' %}">군포시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '의정부시' %}">의정부시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '고양시' %}">고양시</a>
               </li>

               <li>
                  <a href="{% url 'main:location_detail' '오산시' %}">오산시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '안양시' %}">안양시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '의왕시' %}">의왕시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '가평군' %}">가평군</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '양평군' %}">양평군</a>
               </li>
            </ul>
         </li>


         <li class="first_list">
            <a href="{% url 'main:location_detail' '강원도' %}">강원도</a>
            <ul>
         </li>
               <li>
                  <a href="{% url 'main:location_detail' '춘천시' %}">춘천시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '원주시' %}">원주시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '삼척시' %}">삼척시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '강릉시' %}">강릉시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '동해시' %}">동해시</a>
               </li>
            </ul>
         </li>

         <li class="first_list">
            <a href="{% url 'main:location_detail' '충청북도' %}">충청북도</a>
               <ul>
         </li>
               <li>
                  <a href="{% url 'main:location_detail' '청주시' %}">청주시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '충주시' %}">충주시</a>
               </li>
            </ul>
         </li>

         <li class="first_list">
            <a href="{% url 'main:location_detail' '충청남도' %}">충청남도</a>
               <ul>
         </li>
               <li>
                  <a href="{% url 'main:location_detail' '논산시' %}">논산시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '서산시' %}">서산시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '아산시' %}">아산시</a>
               </li>

               <li>
                  <a href="{% url 'main:location_detail' '공주시' %}">공주시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '천안시' %}">천안시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '당진시' %}">당진시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '보령시' %}">보령시</a>
               </li>
            </ul>
         </li>

         <li class="first_list">
            <a href="{% url 'main:location_detail' '전라북도' %}">전라북도</a>
               <ul>
         </li>
               <li>
                  <a href="{% url 'main:location_detail' '군산시' %}">군산시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '남원시' %}">남원시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '정읍시' %}">정읍시</a>
               </li>
            </ul>
         </li>

         <li class="first_list">
            <a href="{% url 'main:location_detail' '전라남도' %}">전라남도</a>
            <ul>
         </li>
               <li>
                  <a href="{% url 'main:location_detail' '광주광역시' %}">광주광역시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '나주시' %}">나주시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '순천시' %}">순천시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '광양시' %}">광양시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '여수시' %}">여수시</a>
               </li>
            </ul>
         </li>


         <li class="first_list">
            <a href="{% url 'main:location_detail' '경상북도' %}">경상북도</a>
            <ul>
         </li>
               <li>
                  <a href="{% url 'main:location_detail' '대구광역시' %}">대구광역시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '김천시' %}">김천시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '영천시' %}">영천시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '경주시' %}">경주시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '상주시' %}">상주시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '구미시' %}">구미시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '영주시' %}">영주시</a>
               </li>
            </ul>
         </li>


         <li class="first_list">
            <a href="{% url 'main:location_detail' '경상남도' %}">경상남도</a>
            <ul>
         </li>
         <li>
                  <a href="{% url 'main:location_detail' '부산광역시' %}">부산광역시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '창원시' %}">창원시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '밀양시' %}">밀양시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '통영시' %}">통영시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '거제시' %}">거제시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '사천시' %}">사천시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '진주시' %}">진주시</a>
               </li>
               <li>
                  <a href="{% url 'main:location_detail' '양산시' %}">양산시</a>
               </li>
            </ul>
         </li>


         <li class="first_list">
            <a href="{% url 'main:location_detail' '제주특별자치도' %}">제주특별자치도</a>
            <ul>
         </li>
      </div>
   </div>

{% endblock %}

templates/location/location_detail.html
{% extends 'base.html' %}
{% block content%}
{% load static %}

<link href="{% static 'css/tables.css' %}" rel="stylesheet"/>



<img src="{% static 'images/home1.jpg'%}" alt="" class="home__img">

<div class="test">
    <span class="result">"{{area}}" 검색결과</span>
    <a href="{% url 'main:location' %}" class="button"><i class="fas fa-undo"></i> 뒤로가기</a>
    <div class="box2">
        {% if camping_list %} 
        <table border="1" width="100%" height="60px;">
            <th>Name</th>
            <th>Address</th>
            {% for camping in camping_list %}
                <tr>
                    <td>
                        <a href="{% url 'main:camping_detail' area camping.id %}">{{ camping.name }}</a>
                        <td>
                        {{ camping.location }}
                        </td>
                    </td>
                </tr>
            {% endfor %}
        </table>

        {% else %}
        <table border="1" width="100%" height="60px;">
            <tr>
                <td>
                    "{{area}}" 검색 결과가 없습니다.
                </td>
            </tr>
        </table>
        {% endif %}

    </div>

    <div class=page>
        <ul class="pagination">
            {% if camping_list.has_previous %}
            <li class = "page-item">
                <a class="page-link" href="?page=1"><img src="{% static 'images/btn_pre00.png'%}"></a>
            </li>
            <li class = "page-item">
                <a class="page-link" href="?page={{ camping_list.previous_page_number }}"><img src="{% static 'images/btn_pre01.png'%}"></a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><img src="{% static 'images/btn_pre00.png'%}"></a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><img src="{% static 'images/btn_pre01.png'%}"></a>
            </li>
            {% endif %}
            {% for page_number in camping_list.paginator.page_range %}
            {% if page_number >= camping_list.number|add:-5 and page_number <= camping_list.number|add:5 %}
                {% if page_number == camping_list.number %}
                <li class="page-item-num active" aria-current="page">
                    <a class="page-link" href="?page={{page_number}}">{{page_number}}</a>
                </li>
                {% else %}
                <li class="page-item-num">
                    <a class="page-link" href="?page={{page_number}}">{{page_number}}</a>
                </li>
                {% endif %}
            {% endif %}
            {% endfor %}
        
            {% if camping_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{camping_list.next_page_number}}"><img src="{% static 'images/btn_next01.png'%}"></a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{camping_list.paginator.num_pages}}"><img src="{% static 'images/btn_next00.png'%}"></a>
            </li>
            {% else %}
            <li class = "page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><img src="{% static 'images/btn_next01.png'%}"></a>
            </li>
            <li class = "page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><img src="{% static 'images/btn_next00.png'%}"></a>
            </li>
            {% endif %}
        </ul>
        </div>
</div>

{% endblock %}

templates/location/search.html
{% extends 'base.html' %}
{% block content%}
{% load static %}
<link href="{% static 'css/table.css' %}" rel="stylesheet"/>
{% comment %} <link href="{% static 'css/styles.css'%}" rel="stylesheet" /> {% endcomment %}

<img src="{% static 'images/home1.jpg'%}" alt="" class="home__img">



      <div class="value">
        입력한 내용이 맞으면 찾기를 눌러주세요</br>
        검색 내용: <strong>{{search}}</strong></br>
        <div class="value-button">
            <a href="{% url 'main:search_val' radio search %}">찾기</a>
            <a href="{% url 'main:location' %}">돌아가기</a>
        </div>

      </div>


{% endblock %}