common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView, PasswordResetCompleteView



app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('password_reset/', 
    PasswordResetView.as_view(template_name='common/password_reset_form.html'), 
    name='password_reset'),


    path('password_reset/done/', 
    PasswordResetDoneView.as_view(
        template_name='common/password_reset_done.html'), 
    name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/ ', 
    PasswordResetConfirmView.as_view(
        template_name='common/password_reset_confirm.html'), 
    name='password_reset_confirm'),

    path('reset/done/', 
    PasswordResetCompleteView.as_view(
        template_name='common/password_reset_complete.html'), 
    name='password_reset_complete'),


    path('delete/', views.delete, name='delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('common/', include('django.contrib.auth.urls')),
    path('',views.index,name='index'),
]

main/urls.py
from django.urls import path
# from .views import index, detail, answer_create
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:id>/<int:comment_id>/', views.detail, name = "detail"),
    path('comment/create/<str:id>/<int:num>', views.comment_create, name='comment_create'),
    path('comment/modify/<str:id>/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<str:id>/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    #path('camping_detail/', views.camping_detail, name='camping_detail'),   
    path('db/', views.db, name='db'),
    path('receive_data/', views.receive_data, name='receive_data'),

    path('answer/create/<str:id>/<int:comment_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<str:id>/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<str:id>/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    
    path('vote/comment/<str:id>/<int:comment_id>', views.vote_comment, name = "vote_comment"),
    path('vote/answer/<str:id>/<int:answer_id>', views.vote_answer, name = "vote_answer"),
    
    path('location/', views.location, name='location'),
    path('location/<str:id>/', views.location_detail, name='location_detail'),
    path('camping_detail/<str:id>/<int:num>', views.camping_detail, name='camping_detail'), 

    path('search/', views.search, name="search"),
    path('search/<str:radio>/<str:search>', views.search_val, name="search_val"),
]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")

common/views.py
# Create your views here.
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

def signup(request):
    """
    회원가입
    """
    
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


def delete(request) :
    if request.user.is_authenticated :
        request.user.delete()
        auth_logout(request) # 세션 지워주기
        
    return redirect('articles:index')

templates/common/login.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link href="{% static 'css/styles.css'%}" rel="stylesheet" />
<link href="{% static 'css/accounts.css' %}" rel="stylesheet"/>
<img src="{% static 'images/home1.jpg'%}" alt="" class="home__img">
<div class="box1">

    <div class="container my-3">
        <div class="login">
            <div class="row">
                <div class="col-12 text-center">
                    <font size = "6">로그인</font>
                </div>
                <div class="col-12 text-right">
                    <span>
                        <a class="join" href="{% url 'common:signup' %}">>회원가입</a>
                    </span>
                </div>
            </div>

        <div class="mt-5 text-center">
            <form method="post" class="post-form" action="{% url 'common:login' %}">
                {% csrf_token %}
                {% include "form_errors.html" %}
                <div class="form-group">
                   
                    <label for="username">사용자ID &nbsp</label>
                    <input type="text"  name="username" id="username" 
                    value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="form-group">
                    <label for="password">비밀번호 &nbsp</label>
                    <input type="password"  name="password" id="password" 
                        value="{{ form.password.value|default_if_none:'' }}">
                </div>
                <button type="submit" class="btn btn-primary">로그인</button>
                <div class="col-8 text-right">
                    <span>
                    </div>
                    <br>
                    <a class="join" href="{% url 'common:password_reset' %}">비밀번호를 잊어버리셨나요?</a>
                </span>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/common/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link href="{% static 'css/styles.css'%}" rel="stylesheet" />
<img src="{% static 'images/home1.jpg'%}" alt="" class="home__img">

<div class = "password_reset_complete">
<div class="mt-5 text-center">
    <br><br>
    <i class="far fa-check-circle fa-3x" style="color:green"></i><br><br>
    <font size = "6" style="color:white" ><b>비밀번호가 변경되었습니다!<b></font>
</div>
</div>
{% endblock %}

templates/common/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link href="{% static 'css/styles.css'%}" rel="stylesheet" />
<link href="{% static 'css/accounts.css' %}" rel="stylesheet"/>
<img src="{% static 'images/home1.jpg'%}" alt="" class="home__img">
<div class="mt-5 text-center">
    <h1 class="text-center mb-5">Input your new password</h1>

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
    
        {% for field in form %}
            <div class="form-group">
                {{ field.label }}
                {{ field }}
            </div>

            <% if field.errors %>
                <div class="alert alert-danger">
                    {{ field.error}}
                </div>
            {% endif %}
        {% endfor %}

        <button type="submit" class="btn btn-success">Reset Password</button>
    </form>


</div>

{% endblock %}

templates/common/password_reset_done.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link href="{% static 'css/styles.css'%}" rel="stylesheet" />
<link href="{% static 'css/accounts.css' %}" rel="stylesheet"/>
<img src="{% static 'images/home1.jpg'%}" alt="" class="home__img">

<div class = "password_reset_done">
    <div class="mt-5 text-center">
        <h1 class="text-center mb-5">이메일을 보냈습니다</h1>
        <div class="alert alert-info">입력하신 이메일을 확인해주세요</div>    


    </div>
</div>
{% endblock %}

templates/common/password_reset_form.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link href="{% static 'css/styles.css'%}" rel="stylesheet" />
<link href="{% static 'css/accounts.css' %}" rel="stylesheet"/>
<img src="{% static 'images/home1.jpg'%}" alt="" class="home__img">
<div class = "password_reset_form">
<div class="mt-5 text-center">
    <h1 class="text-center mb-5">비밀번호 변경</h1>
    <div class="alert alert-info mb-5">가입시 등록하였던 이메일을 입력해주세요</div>    

    <form method="post">
        {% csrf_token %}
    
        {% for field in form %}
            <div class="form-group">
                {{ field.label }}
                {{ field }}</div>
        {% endfor %}

        <button type="submit" class="btn btn-success">변경</button>
    </form>
</div>
</div>

{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link href="{% static 'css/styles.css'%}" rel="stylesheet" />
<link href="{% static 'css/accounts.css'%}" rel="stylesheet" />
<img src="{% static 'images/home1.jpg'%}" alt="" class="home__img">
<div class="container my-3">
    <div class="login">
        <div class="row my-3">
            <div class="col-12 text-center">
                <font size = "6">회원가입</font>
            </div>
            <div class="col-12 text-right">
                <a class="join" href="{% url 'common:login' %}">로그인</a>
            </div>
        </div>
        <form method="post" class="post-form">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="form-group">
                <label for="username">사용자 이름</label>
                <input type="text" class="form-control" 
                name="username" id="username" 
                value="{{ form.username.value|default_if_none:'' }}">
            </div>
            
            <div class="form-group">
                <label for="password1">비밀번호</label>
                <input type="password" class="form-control" name="password1" id="password1" 
                value="{{ form.password1.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="password2">비밀번호 확인</label>
                <input type="password" class="form-control" name="password2" 
                id="password2" value="{{ form.password2.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="email">이메일</label>
                <input type="text" class="form-control" name="email" id="email"
                value="{{ form.email.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-primary">생성하기</button>
        </form>
    </div>
</div>
{% endblock %}