common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView, PasswordResetCompleteView



app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('password_reset/', 
    PasswordResetView.as_view(template_name='common/password_reset_form.html'), 
    name='password_reset'),


    path('password_reset/done/', 
    PasswordResetDoneView.as_view(
        template_name='common/password_reset_done.html'), 
    name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/ ', 
    PasswordResetConfirmView.as_view(
        template_name='common/password_reset_confirm.html'), 
    name='password_reset_confirm'),

    path('reset/done/', 
    PasswordResetCompleteView.as_view(
        template_name='common/password_reset_complete.html'), 
    name='password_reset_complete'),


    path('delete/', views.delete, name='delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('common/', include('django.contrib.auth.urls')),
    path('',views.index,name='index'),
]

main/urls.py
from django.urls import path
# from .views import index, detail, answer_create
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:id>/<int:comment_id>/', views.detail, name = "detail"),
    path('comment/create/<str:id>/<int:num>', views.comment_create, name='comment_create'),
    path('comment/modify/<str:id>/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<str:id>/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    #path('camping_detail/', views.camping_detail, name='camping_detail'),   
    path('db/', views.db, name='db'),
    path('receive_data/', views.receive_data, name='receive_data'),

    path('answer/create/<str:id>/<int:comment_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<str:id>/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<str:id>/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    
    path('vote/comment/<str:id>/<int:comment_id>', views.vote_comment, name = "vote_comment"),
    path('vote/answer/<str:id>/<int:answer_id>', views.vote_answer, name = "vote_answer"),
    
    path('location/', views.location, name='location'),
    path('location/<str:id>/', views.location_detail, name='location_detail'),
    path('camping_detail/<str:id>/<int:num>', views.camping_detail, name='camping_detail'), 

    path('search/', views.search, name="search"),
    path('search/<str:radio>/<str:search>', views.search_val, name="search_val"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link
    rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
    integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
    crossorigin="anonymous"
    />
    <title>IoT-1조</title>
  </head>
  <body>
    {% include "navbar.html" %} {% block content %}{% endblock %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block script %}{% endblock %}

  </body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %} <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}
<link href="{% static 'css/styles.css'%}" rel="stylesheet" />
  <div class="navbar border-bottom">
    <img src="{% static 'images/home2.jpg'%}" alt="" class="nav__img">
    <a class="logo" href="{% url 'main:index' %}">
      <img src="{% static 'images/logo.png' %}" height="80px">
      <span class="logo_name">Camping Log</span>
    </a>
    <ul>
      <li  class = "nav-item">
        {% if user.is_authenticated %}
        <a class="nav" href="{% url 'common:logout' %}">
          {{ user.username }} (로그아웃)</a>
        {% else %}
        <li><a class="nav" href="{% url 'common:login' %}">로그인</a></li>
        {% endif %}

     
    </ul>
  </div>